In [1]:
import pandas as pd
import requests

In [10]:
play_by_play_url = "https://cdn.nba.com/static/json/liveData/playbyplay/playbyplay_0042000404.json"
response = requests.get(url=play_by_play_url).json()
play_by_play = response['game']['actions']
df = pd.DataFrame(play_by_play)
print(df.shape)
df.head()

(567, 54)

,actionNumber,clock,timeActual,period,periodType,actionType,subType,qualifiers,personId,x,...,stealPlayerName,stealPersonId,officialId,foulPersonalTotal,foulTechnicalTotal,foulDrawnPlayerName,foulDrawnPersonId,blockPlayerName,blockPersonId,value
0,2,PT12M00.00S,2021-07-15T01:11:34.8Z,1,REGULAR,period,start,[],0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,PT11M55.00S,2021-07-15T01:11:38.9Z,1,REGULAR,jumpball,recovered,[],203109,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,PT11M44.00S,2021-07-15T01:11:49.7Z,1,REGULAR,2pt,Jump Shot,[],1626164,21.501314,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,PT11M22.00S,2021-07-15T01:12:11.2Z,1,REGULAR,2pt,Jump Shot,[],203114,71.616294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10,PT11M19.00S,2021-07-15T01:12:14.2Z,1,REGULAR,rebound,defensive,[],203109,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.to_clipboard()

In [11]:
df.to_csv('2021-07-15_mil-vs-phoenix_pbp.csv')